# Generated by Django 5.2.1 on 2025-06-09 21:50

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparte',
            options={'verbose_name_plural': 'Autopartes'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name_plural': 'Modelos'},
        ),
        migrations.AddField(
            model_name='autoparte',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoparte',
            name='imagen',
            field=models.ImageField(default='', upload_to='autopartes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autoparte',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
