# Generated by Django 5.2.1 on 2025-06-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopartes', '0002_alter_autoparte_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autopartes/'),
        ),
    ]
